# Generated by Django 5.0.4 on 2024-04-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_author_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount',
        ),
    ]
