# Generated by Django 5.0.4 on 2024-05-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courselanguage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLanguage',
        ),
    ]
