# Generated by Django 5.0.4 on 2024-06-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_delete_courselanguage'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructor.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
