# Generated by Django 5.0.4 on 2024-06-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_video_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='completed_by',
        ),
    ]
