# Generated by Django 5.0.4 on 2024-06-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_video_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='img',
            field=models.ImageField(null=True, upload_to='Media/Category'),
        ),
    ]
