# Generated by Django 5.0.4 on 2024-06-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_categories_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='img',
        ),
    ]
