# Generated by Django 5.0.4 on 2024-06-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_categories_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
