# Generated by Django 5.0.6 on 2024-06-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='featured_video',
        ),
    ]
