# Generated by Django 5.0.4 on 2024-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Default Option 1', max_length=255, verbose_name='Option 1'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Default Option 2', max_length=255, verbose_name='Option 2'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Default Option 3', max_length=255, verbose_name='Option 3'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Default Option 4', max_length=255, verbose_name='Option 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='Default Option 1', help_text='Enter the correct answer exactly as one of the options', max_length=255),
        ),
    ]
