# Generated by Django 5.0.4 on 2024-05-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_question_option1_question_option2_question_option3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
    ]
