# Generated by Django 5.0.4 on 2024-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_question_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='total_time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
