# Generated by Django 5.0.4 on 2024-06-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_quizattempt_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='start_time',
        ),
    ]
