# Generated by Django 5.0.6 on 2024-06-12 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_remove_quizattempt_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Title must not contain numbers.', regex='^[^\\d]*$')]),
        ),
    ]
