# Generated by Django 5.0.4 on 2024-06-04 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must only contain alphabetic characters.', regex='^[a-zA-Z]+$')]),
        ),
    ]
